FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
# You will need to change this port to match each specific app (e.g., 4000, 3000, 5173)
EXPOSE 4000
CMD ["npm", "start"]